import { GoogleGenAI, Modality } from '@google/genai';
import { Preset, AspectRatio } from '../types';

function base64ToInlineData(base64: string) {
    const [mimePart, dataPart] = base64.split(';base64,');
    if (!mimePart || !dataPart) {
        throw new Error('Invalid base64 string for image upload.');
    }
    const mimeType = mimePart.split(':')[1];
    return {
        inlineData: {
            data: dataPart,
            mimeType,
        },
    };
}

export async function generateImage(ai: GoogleGenAI, imageBase64: string, preset: Preset, aspectRatio: AspectRatio): Promise<string> {
    const prompt = aspectRatio === 'Free'
        ? preset.prompt
        : `${preset.prompt}. The final image should be in a ${aspectRatio} aspect ratio.`;

    const imagePart = base64ToInlineData(imageBase64);
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                imagePart,
                { text: prompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }
    
    throw new Error('No image was generated by the API.');
}
